services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - BACKEND_URL=http://backend:8080
      - NODE_ENV=development
    command: sh -lc "npm ci && npm run dev -- -H 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - backend
