services:
  backend:
    build:
      context: ./backend
      args:
        SERVICE_ID: ${SERVICE_ID}
    environment:
      SERVICE_ID: ${SERVICE_ID}
      DATABASE_URL: ${DATABASE_URL}
      PORT: "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        # プロキシ方式: クライアントは /api を叩く
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-/api}
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-/api}
      # Auth0 required envs for login to work locally
      AUTH0_SECRET: ${AUTH0_SECRET:-}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL:-http://localhost:3000}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL:-}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID:-}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET:-}
      PORT: "3000"
    ports:
      - "3000:3000"

