version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bini
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 15

  backend:
    build:
      context: ./backend
      args:
        SERVICE_ID: ${SERVICE_ID}
    environment:
      SERVICE_ID: ${SERVICE_ID}
      # Railway の DB を使うため .env から DATABASE_URL を渡す
      DATABASE_URL: ${DATABASE_URL}
      PGHOST: db
      PGPORT: "5432"
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: bini
      PGSSLMODE: disable
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        # ビルド時に API を埋め込む（env から受け取る）。未設定なら backend を参照
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://backend:8080}
    environment:
      # ランタイムで上書きしたい場合に使用（未設定ならビルド時の値が使われます）
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://backend:8080}
      PORT: "3000"
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  dbdata:
